1 parcial
prefeitura-rio/queries-rj-sms pull request #21
Opened 2024-03-20 19:51 UTC by daniloffonseca

Edição da descrição das tabelas 

rj-sms.brutos_estoque_central_tpc.estoque_posicao
rj-sms.brutos_plataforma_smsrio
rj-sms.brutos_sheets.estabelecimento_auxiliar
rj-sms.projeto_dengue

2024-03-21 19:24 UTC, ThiagoTrabach requested changes
Olhar os dois comentários

2024-03-21 19:24 UTC, ThiagoTrabach commented on models/raw/plataforma_smsrio/_plataforma_smsrio_schema.yml
este dedataset é de posição de estoque, não de movimento. Ajustar as descrições que fazem referência a movimentação de estoque

2024-03-21 19:24 UTC, ThiagoTrabach commented on models/raw/sheets/_sheets_schema.yml
Essa descrição está muito vaga. Em outra tabela existe uma descrição boa. Busca ela no projeto

2024-03-25 20:04 UTC, daniloffonseca commented on models/raw/sheets/_sheets_schema.yml
>    - name: raw_sheets__material_remume
alterado para Campo com unidades classificadas por tipo padrão da SMS. Não encontrei colunas iguais com descrição.

2024-04-23 20:04 UTC, closed without merging