Mudança de estrutura dos campos CBO e conselho
prefeitura-rio/queries-rj-sms pull request #45
Opened 2024-06-26 14:49 UTC by vitmesquita

## Descrição & motivação

## Issues Relacionadas

## Tipo de Mudança

- [ ] Novo modelo
- [ ] Correção de bug
- [x] Refatoração
- [ ] Mudança que quebra compatibilidade
- [x] Documentação
- [ ] Atualização/Instalação de dependências

## A fazer antes do merge

Em caso de quebra de compatibilidade
- [x] Validar em dev o funcionamento correto dos produtos de dados afetados

## DAG de Linhagem:

## Validação dos modelos:

## Considerações de Impacto:

## Mudanças nos modelos existentes:

## Lista de Verificação:

- [ ] Meu pull request representa uma peça lógica de trabalho.
- [ ] Meus commits estão relacionados ao pull request e parecem limpos.
- [ ] Meu SQL segue o [guia de estilo da SMS-Rio](https://doc.clickup.com/9013004335/d/h/8ckf21f-1073/e8ed96d7bccb902/8ckf21f-14653).
- [ ] `dbt build` completa com sucesso e os testes dbt passam (se não, detalhe por quê)
- [ ] Materializei meus modelos apropriadamente.
- [ ] Adicionei testes e documentação apropriados a quaisquer modelos novos.
- [ ] Adicionei policy tags apropriadas a quaisquer modelos novos.
- [ ] Atualizei o arquivo README.

2024-07-01 20:46 UTC, ThiagoTrabach commented
@vitmesquita adiciona no PR a linhagem, diferença de schema e pelo menos o count de registros e de distinct id do profissional antes e depois

2024-07-01 21:10 UTC, vitmesquita commented
Linhagem atual:
![image](https://github.com/prefeitura-rio/queries-rj-sms/assets/41980417/f2af089b-69eb-4574-a221-3b36b4f19232)
Diferença de schema e contagem de linhas:
![image](https://github.com/prefeitura-rio/queries-rj-sms/assets/41980417/b3f57111-b7ec-43b9-af86-31989e858141)
![image](https://github.com/prefeitura-rio/queries-rj-sms/assets/41980417/2b69f0a5-5e08-4a9f-94f2-ecd48baac348)
Contagem de id_profissional_sus:
![image](https://github.com/prefeitura-rio/queries-rj-sms/assets/41980417/c69d1bba-bb5a-4936-b2cd-1b1800638877)

2024-07-01 21:37 UTC, ThiagoTrabach requested changes

2024-07-01 21:37 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_profissional_saude.sql
>      current_date('America/Sao_Paulo') as data_referencia
Pode tirar esta data de referência. Por definição desta tabela, ele é sempre a relação vigente. Este campo não adiciona nenhuma informação nova.

2024-07-04 16:55 UTC, ThiagoTrabach approved these changes

2024-07-04 16:55 UTC, merged