Criando tabela mestre de equipes
prefeitura-rio/queries-rj-sms pull request #46
Opened 2024-06-27 17:57 UTC by vitmesquita

## Descrição & motivação

## Issues Relacionadas

## Tipo de Mudança

- [x] Novo modelo
- [ ] Correção de bug
- [ ] Refatoração
- [ ] Mudança que quebra compatibilidade
- [x] Documentação
- [ ] Atualização/Instalação de dependências

## A fazer antes do merge

Em caso de quebra de compatibilidade
- [ ] Validar em dev o funcionamento correto dos produtos de dados afetados

## DAG de Linhagem:

## Validação dos modelos:

## Considerações de Impacto:

## Mudanças nos modelos existentes:

## Lista de Verificação:

- [ ] Meu pull request representa uma peça lógica de trabalho.
- [ ] Meus commits estão relacionados ao pull request e parecem limpos.
- [ ] Meu SQL segue o [guia de estilo da SMS-Rio](https://doc.clickup.com/9013004335/d/h/8ckf21f-1073/e8ed96d7bccb902/8ckf21f-14653).
- [ ] `dbt build` completa com sucesso e os testes dbt passam (se não, detalhe por quê)
- [ ] Materializei meus modelos apropriadamente.
- [ ] Adicionei testes e documentação apropriados a quaisquer modelos novos.
- [ ] Adicionei policy tags apropriadas a quaisquer modelos novos.
- [ ] Atualizei o arquivo README.

2024-07-01 21:09 UTC, ThiagoTrabach requested changes

2024-07-01 21:09 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_equipe.sql
> +    dim_area_segmento.segmento_descricao,
Achei bem zoneado essa campo da forma que vêm do CNES. Ele é realmente necessário? Se for, conseguimos padronizá-lo?

2024-07-01 21:09 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_equipe.sql
> +    equipe.equipe_ine as ine,
chamar de id_ine

2024-07-01 21:09 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_equipe.sql
> +    dim_tipo_equipe.equipe_descricao as equipe_tipo_descricao,
remover espaços duplos
![image](https://github.com/prefeitura-rio/queries-rj-sms/assets/7233184/73834f9c-67d3-4007-bd21-ea0a6fcba915)

2024-07-01 21:09 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_equipe.sql
> +    dim_area_segmento.segmento_descricao,
Parece ser só a área programática. Já obtemos isso a partir do estabelecimento. Pode limar
![image](https://github.com/prefeitura-rio/queries-rj-sms/assets/7233184/2a0940bf-c72d-4f17-b086-3478312b9f74)

2024-07-01 21:09 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_equipe.sql
> +    equipe.id_unidade as id_unidade_saude,
Substituir pelo identificador da dim_estabelecimento (id_cnes)

2024-07-02 14:30 UTC, vitmesquita commented on models/marts/core/dimensions/dim_equipe.sql
```sql
WITH  equipe as (
  SELECT * 
  FROM rj-sms-dev.saude_dados_mestres.equipe_profissional_saude),
profissional as (
    SELECT * 
    FROM rj-sms-dev.saude_dados_mestres.profissional_saude
  )
  
SELECT  ine,
medicos,
ARRAY(
    SELECT nome 
    FROM UNNEST(medicos) AS id 
    JOIN profissional 
    ON profissional.id_profissional_sus = id
  ) AS medicos_nome
FROM  equipe
```

2024-07-02 17:59 UTC, vitmesquita commented on models/marts/core/dimensions/dim_equipe.sql
Output:
![image](https://github.com/prefeitura-rio/queries-rj-sms/assets/41980417/b8d74755-ed52-4ffb-b050-45904dcf9879)

2024-07-02 19:29 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_equipe.sql
> +        from {{ ref("raw_cnes_web__equipe_profissionais") }} as equipe_p
boa, tem razão

2024-07-16 20:22 UTC, ThiagoTrabach approved these changes

2024-07-16 20:27 UTC, merged