Implementing other vitai models
prefeitura-rio/queries-rj-sms pull request #49
Opened 2024-07-05 19:22 UTC by TanookiVerde

## Descrição & motivação

## Issues Relacionadas

## Tipo de Mudança

- [ ] Novo modelo
- [ ] Correção de bug
- [ ] Refatoração
- [ ] Mudança que quebra compatibilidade
- [ ] Documentação
- [ ] Atualização/Instalação de dependências

## A fazer antes do merge

Em caso de quebra de compatibilidade
- [ ] Validar em dev o funcionamento correto dos produtos de dados afetados

## DAG de Linhagem:

## Validação dos modelos:

## Considerações de Impacto:

## Mudanças nos modelos existentes:

## Lista de Verificação:

- [ ] Meu pull request representa uma peça lógica de trabalho.
- [ ] Meus commits estão relacionados ao pull request e parecem limpos.
- [ ] Meu SQL segue o [guia de estilo da SMS-Rio](https://doc.clickup.com/9013004335/d/h/8ckf21f-1073/e8ed96d7bccb902/8ckf21f-14653).
- [ ] `dbt build` completa com sucesso e os testes dbt passam (se não, detalhe por quê)
- [ ] Materializei meus modelos apropriadamente.
- [ ] Adicionei testes e documentação apropriados a quaisquer modelos novos.
- [ ] Adicionei policy tags apropriadas a quaisquer modelos novos.
- [ ] Atualizei o arquivo README.

2024-07-06 00:11 UTC, ThiagoTrabach requested changes

2024-07-06 00:11 UTC, ThiagoTrabach commented on profiles.yml
@TanookiVerde . Qual motivo do perfil compile?

2024-07-06 00:11 UTC, ThiagoTrabach commented on models/raw/prontuario_vitai/raw_prontuario_vitai__alergia.sql
> +        tags=["vitai_db", "every_30_min"],
@TanookiVerde você pode passar as tags no nível do projeto também
<img width="408" alt="image" src="https://github.com/prefeitura-rio/queries-rj-sms/assets/7233184/5b51d28a-c182-4157-b43b-37a412e71ad7">

2024-07-08 12:43 UTC, TanookiVerde commented on models/raw/prontuario_vitai/raw_prontuario_vitai__alergia.sql
> +        tags=["vitai_db", "every_30_min"],
para Pedro: 
- utilizar "model disable" nos modelos de estoque:
  - https://docs.getdbt.com/reference/resource-configs/enabled
- subir tag p/ dataset

2024-07-08 13:54 UTC, ThiagoTrabach approved these changes

2024-07-08 13:55 UTC, merged