Feature: Adiciona modelos iniciais de paciente
prefeitura-rio/queries-rj-sms pull request #63
Opened 2024-07-29 20:09 UTC by d116626

### Feature: Adiciona modelos iniciais de paciente"

### Estratégia
**Ciclo 1 - MVP**

- Expectativa: Entre 5.8 e 6.2M (apenas se todos os registros tivessem CPF)
- Objetivo: trazer registros com CPF não nulo

- Limitações:
  - Problema I: Existirão registros conflitantes: e.g. mesmo CPF, mas nomes diferentes. 
Enquanto isso, escolhemos como confiável a data de nascimento mais velha.

**Ciclo 2**
- Se atentar para problema I Existirão registros conflitantes

Descrição: adiciona modelos de cada fonte de dados seguindo o payload:

```json

{
    "nome_civil": "Thiago Trabach",
    "nome_social": null,
    "cpf": "12345678900",
    "cns": [
      { 
        "valor": "123456789012345"
        "rank": 1,
      },
      { 
        "valor": "123456789012345"
        "rank": 2,
      }
    ],
    "data_nascimento": "1990-01-01",
    "genero": "male",
    "raca": "branca",
    "obito_indicador": false,
    "obito_data": null,
    "mae_nome": "Maria da Silva",
    "pai_nome": "João da Silva",
    "cadastro_validado_indicador": true, # Indicar se está na base SMSRio: Significa que foram validados no CADSus
    "clinica_familia": [
        {
            "id_cnes": "1234567",
            "nome": "Clinica da Familia XXX",
            "datahora_ultima_atualizacao": "2024-10-07 12:00:00"
        },
        {
            "id_cnes": "1234567",
            "nome": "Clinica da Familia YYY",
            "datahora_ultima_atualizacao": "2023-01-07 12:00:00"
        }
    ],
    "equipe_saude_familia": [
        {
            "id_ine": "1234567",
            "datahora_ultima_atualizacao": "2024-07-01 12:00:00"
        },
        {
            "id_ine": "9999999",
            "datahora_ultima_atualizacao": "2024-06-01 12:00:00"
        }
    ],
    "contato": [
        {
            "tipo": "telefone",
            "valor": "123456789"
        },
        {
            "tipo": "email",
            "valor": "thiago@gmail.com"
        }
    ],
    "endereco": [
        {
            "cep": "12345678",
            "logradouro": "Rua dos Bobos",
            "numero": "0",
            "complemento": "Casa",
            "bairro": "Bairro",
            "cidade": "Cidade",
            "estado": "Estado",
            "datahora_ultima_atualizacao": "2022-06-21 12:00:00"
        }
    ],
    "prontuario": [
        {
            "fornecedor": "vitacare",
            "id_cnes": "1234567",
            "id_paciente": "12345678900"
        },
        {
            "fornecedor": "vitacare",
            "id_cnes": "999999",
            "id_paciente": "098876654432"
        },
        {
            "fornecedor": "vitai",
            "id_cnes": "5555555",
            "id_paciente": "00000000"
        }
    ],
    "metadados": {
        "data_geracao": "2024-07-01 12:00:00"
    }
}

```

2024-07-30 13:58 UTC, ThiagoTrabach requested changes

2024-07-31 09:01 UTC, ThiagoTrabach requested changes
@d116626 neste review foquei em algumas informações que são cruciais e estão faltando e na questão do ordenamento das informações mais corretas para cada sistema. Isso vai nos ajudar na etapa de merge, pois podemos puxar o rank = 1 de cada sistema. Notei uma grande despadronização nos endereços, mas isso é esperado e não será nosso foco no momento. Vou criar um board no Click up para anotarmos esses débitos e voltarmos no futuro.

2024-07-31 15:01 UTC, d116626 commented on models/intermediate/paciente/smsrio.sql
> +smsrio_contato AS (
feito

2024-07-31 15:04 UTC, d116626 commented on models/intermediate/paciente/vitai.sql
> +        ROW_NUMBER() OVER (PARTITION BY cpf ORDER BY cpf DESC) AS rank
feito

2024-07-31 15:23 UTC, d116626 commented on models/intermediate/paciente/vitai.sql
> +        cliente AS id_cnes,
feito

2024-07-31 15:23 UTC, d116626 commented on models/intermediate/paciente/vatacare.sql
> +        ROW_NUMBER() OVER (PARTITION BY paciente_cpf ORDER BY cns DESC) AS rank
Não ficou claro pra mim qual campo usar em cada um dos ranks

2024-07-31 16:36 UTC, ThiagoTrabach commented on models/intermediate/paciente/vatacare.sql
> +        ROW_NUMBER() OVER (PARTITION BY paciente_cpf ORDER BY cns DESC) AS rank
O nome dos campos são esses mesmos, eles constam na base bruta da Vitacare (rj-sms.brutos_prontuario_vitacare.paciente). Vamos usar esse critério de ordenação para todos as atributos da Vitacare (cns, dados, endereço, ...)

2024-08-28 18:34 UTC, merged