Alterações nas estruturas dos modelos: estabelecimento_sus_rio_historico; estabelecimento_auxiliar.
prefeitura-rio/queries-rj-sms pull request #92
Opened 2024-09-17 20:52 UTC by miloskimatheus

2024-09-18 14:18 UTC, ThiagoTrabach requested changes
@miloskimatheus marquei os ajustes para fazer

2024-09-18 14:18 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_estabelecimento.sql
>  select
boa prática, encapsular a última querie como final e no final dar um select simples. Vai facilitar seu troubleshooting:
<img width="347" alt="image" src="https://github.com/user-attachments/assets/c9dc6925-3d9d-4dba-a3cf-dd46d2eef154">

2024-09-18 14:18 UTC, ThiagoTrabach commented on models/marts/saude_cnes/_mart_saude_cnes_schema.yml
> +      - name: indicador_estabelecimento_sms
Alterar o nome do campo para atendimento_...._indicador. A entendida a que se refere sempre vem primeiro

2024-09-18 14:18 UTC, ThiagoTrabach commented on models/marts/saude_cnes/_mart_saude_cnes_sources.yml
Matar esse arquivo.

O estabelecimento já existe como um modelo:
<img width="342" alt="image" src="https://github.com/user-attachments/assets/8f4ee668-86a4-42b0-b40a-fb1415f3eb17">

2024-09-18 14:18 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_estabelecimento.sql
> +current_period as (
um max(data_particao) não resolve isso?

2024-09-18 14:18 UTC, ThiagoTrabach commented on models/marts/saude_cnes/dim_estabelecimento_sus_rio_historico.sql
> +{{
Adicionar adicionar configuração de particionamento pelo campo data_particao

2024-09-18 14:18 UTC, ThiagoTrabach commented on models/marts/saude_cnes/dim_estabelecimento_sus_rio_historico.sql
> +    -- Indicadores
trazer a entidade para sufixo

2024-09-18 14:18 UTC, ThiagoTrabach commented on models/marts/saude_cnes/dim_estabelecimento_sus_rio_historico.sql
Tem um problema na geração desta tabela. Registros vazios estão sendo gerados
<img width="2095" alt="image" src="https://github.com/user-attachments/assets/cc7159cc-77c0-4685-8491-edc6e7b270f2">

2024-09-18 14:18 UTC, ThiagoTrabach commented on models/marts/core/dimensions/dim_estabelecimento.sql
> +current_period as (
Parece que isso está dando algum problema de tipagem

2024-09-18 14:52 UTC, miloskimatheus commented on models/marts/core/dimensions/dim_estabelecimento.sql
> +current_period as (
tipagem ok, o problema é outro

2024-09-18 15:32 UTC, miloskimatheus commented on models/marts/core/dimensions/dim_estabelecimento.sql
> +current_period as (
aparentemente resolvido. ajustei tipagens e nome da variavel "area_programatica".

2024-09-20 17:33 UTC, miloskimatheus commented on models/marts/saude_cnes/_mart_saude_cnes_schema.yml
> +      - name: indicador_estabelecimento_sms
feito

2024-09-20 17:58 UTC, miloskimatheus commented on models/marts/saude_cnes/dim_estabelecimento_sus_rio_historico.sql
> +    -- Indicadores
feito

2024-09-20 17:58 UTC, miloskimatheus commented on models/marts/saude_cnes/_mart_saude_cnes_sources.yml
resolvido

2024-09-20 18:01 UTC, miloskimatheus commented on models/marts/saude_cnes/dim_estabelecimento_sus_rio_historico.sql
> +{{
feito

2024-09-20 20:16 UTC, miloskimatheus commented on models/marts/saude_cnes/dim_estabelecimento_sus_rio_historico.sql
resolvido

2024-10-09 17:38 UTC, merged